%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV)
Camera.fx: 435.066618695
Camera.fy: 435.066618695
Camera.cx: 368.376438141
Camera.cy: 252.143295288

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0

Camera.bFishEye: 0

Camera.width: 752
Camera.height: 480

# Camera frames per second
Camera.fps: 20.0

# stereo baseline times fx
Camera.bf: 47.824207066

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 35.0

#--------------------------------------------------------------------------------------------
# Stereo Rectification. Only if you need to pre-rectify the images.
# Camera.fx, .fy, etc must be the same as in LEFT.P
#--------------------------------------------------------------------------------------------
LEFT.height: 480
LEFT.width: 752
LEFT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [-0.2873913, 0.0774326, 0.0002425, 7.2e-05, 0.0]

LEFT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [458.7566583, 0.0, 366.2358242, 0.0, 457.4404671, 248.3385405, 0.0, 0.0, 1.0]

LEFT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.9999817221488871, -0.0018288900658730458, 0.00576285773491527, 0.001789055357471033, 0.9999745258988448, 0.006909908415345906, -0.0057753483941513205, -0.006899472045563693, 0.9999595204989143]

LEFT.Rf:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: f
   data: [0.9999817221488871, -0.0018288900658730458, 0.00576285773491527, 0.001789055357471033, 0.9999745258988448, 0.006909908415345906, -0.0057753483941513205, -0.006899472045563693, 0.9999595204989143]

LEFT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [435.06661869496253, 0.0, 368.37643814086914, 0.0, 0.0, 435.06661869496253, 252.14329528808594, 0.0, 0.0, 0.0, 1.0, 0.0]

RIGHT.height: 480
RIGHT.width: 752
RIGHT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [-0.2847054, 0.075288, -4.57e-05, 6.26e-05, 0.0]

RIGHT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [457.3817361, 0.0, 378.9001604, 0.0, 456.0005882, 255.2982812, 0.0, 0.0, 1.0]

RIGHT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.9999775167053501, -0.003971839730873461, 0.005402830087414066, 0.00400905029785992, 0.9999682001143249, -0.006893930361325076, -0.0053752766915239935, 0.0069154355806287, 0.9999616408398972]

RIGHT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [435.06661869496253, 0.0, 368.37643814086914, -47.82420706595531, 0.0, 435.06661869496253, 252.14329528808594, 0.0, 0.0, 0.0, 1.0, 0.0]

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1200

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500


